-- 2019-05-30
-- GOGAK TABLE만들기
CREATE TABLE GOGAK
(
         G_CODE	VARCHAR2(20) PRIMARY KEY
        ,G_NAME	VARCHAR2(20) NOT NULL
        ,G_AGE	NUMBER(3)
        ,G_ADDR	VARCHAR2(50)
        ,G_TEL	VARCHAR2(13)
        ,DELETEYN	VARCHAR2(1) NOT NULL
        ,CREATEDATE	DATE	NOT NULL
        ,UPDATEDATE	DATE	NOT NULL
        ,VIPYN	VARCHAR2(1) NOT NULL
);
DESC GOGAK;
SELECT *     
FROM   GOGAK; 
ROLLBACK;
COMMIT;

-- VIDEO TABLE만들기
CREATE TABLE VIDEO
(
       V_CODE	VARCHAR2(20) PRIMARY KEY
      ,V_TITLE	VARCHAR2(20) NOT NULL
      ,V_GENRE	VARCHAR2(10)
      ,V_PAY	NUMBER(5) NOT NULL
      ,V_RENTSTATE	VARCHAR2(1) NOT NULL
      ,V_MAKECOMPANY	VARCHAR2(20)
      ,V_MAKEDATE	DATE	NOT NULL
      ,V_VIEWAGE	NUMBER(1) NOT NULL
      ,DELETEYN	VARCHAR2(1) NOT NULL
      ,CREATEDATE	DATE	NOT NULL
      ,UPDATEDATE	DATE	NOT NULL
);
DESC VIDEO;
SELECT *     
FROM   VIDEO; 
ROLLBACK;
COMMIT;
-- RENTRETURN TABLE만들기
CREATE TABLE RENTRETURN
(
       R_CODE	VARCHAR2(20) PRIMARY KEY
      ,G_CODE	VARCHAR2(20) REFERENCES GOGAK(G_CODE)
      ,V_CODE	VARCHAR2(20) REFERENCES VIDEO(V_CODE)
      ,R_RENTDATE	DATE	NOT NULL
      ,R_PLANDATE	DATE	NOT NULL
      ,R_RETURNDATE	DATE	
      ,R_TOTALPAY	NUMBER(4) NOT NULL
      ,R_OVERDUEDATE	NUMBER(2) 
      ,DELETEYN	VARCHAR2(1) NOT NULL
      ,CREATEDATE	DATE	NOT NULL
      ,UPDATEDATE	DATE	NOT NULL
);
DESC RENTRETURN;
SELECT *     
FROM   RENTRETURN; 
ROLLBACK;
COMMIT;
